"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, BadgeCheck, Check, ChevronRight, Copy, Download, FileBadge, MoreHorizontal, Pencil, Share2, Sparkles } from "lucide-react";
import type { IssuedCertificate } from "@/lib/platform/types";
import { MemberShell, PlaceholderArt } from "@/components/member/member-shell";
import { useAuth } from "@/components/auth/auth-context";

export function CertificateArtwork({ certificate, name }: { certificate: IssuedCertificate; name?: string }) {
  return <div className="issued-certificate-art"><span className="issued-logo">Coursiv</span><h2>MASTER OF {certificate.courseTitle.toUpperCase()}</h2><small>ISSUED TO</small><strong>{name ?? certificate.learnerName}</strong><p>Awarded for the successful completion of the {certificate.courseTitle} course and demonstration of practical AI skills.</p><div className="certificate-seal"><i>✦</i></div><div className="certificate-meta"><span>Date of issue<b>{new Date(certificate.issuedAt).toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"})}</b></span><span>Course length<b>{certificate.courseHours} hours</b></span></div><em>{certificate.credentialId}</em></div>;
}

export function CertificatesListPage() {
  const auth=useAuth();const [certificates,setCertificates]=useState<IssuedCertificate[]>([]);const [error,setError]=useState("");const [loading,setLoading]=useState(true);
  useEffect(()=>{if(!auth.user)return;let active=true;void(async()=>{try{const token=await auth.getToken();const response=await fetch("/api/certificates/issue",{method:"POST",headers:token?{Authorization:`Bearer ${token}`}:{}});const data=await response.json();if(!response.ok)throw new Error(data.error);if(active)setCertificates(data.certificates as IssuedCertificate[]);}catch(reason){if(active)setError(reason instanceof Error?reason.message:"Unable to load certificates");}finally{if(active)setLoading(false);}})();return()=>{active=false};},[auth]);
  return <MemberShell title="Certificates"><div className="member-content certificates-list"><section className="certificate-count"><FileBadge/><div><strong>{certificates.length}</strong><span>Certificates earned</span></div><p>Every finished course and passed program becomes a verified Coursiv credential.</p></section><h2>Your achievements</h2>{certificates.length?certificates.map((certificate,index)=><Link href={`/certificates/${certificate.id}`} key={certificate.id}><PlaceholderArt index={index} label={certificate.courseTitle}/><span><small>CERTIFICATE OF COMPLETION</small><strong>{certificate.courseTitle}</strong><em><BadgeCheck/>Verified · {new Date(certificate.issuedAt).toLocaleDateString("en-GB")}</em></span><ChevronRight/></Link>):<p>{loading?"Checking your achievements…":"Complete a course and pass each program skills check to earn your first certificate."}</p>}{error&&<p role="alert">{error}</p>}</div></MemberShell>;
}

export function CertificateDetailPage({ certificateId }: { certificateId:string }) {
  const auth=useAuth();const [certificate,setCertificate]=useState<IssuedCertificate|null>(null);const [error,setError]=useState("");
  useEffect(()=>{if(!auth.user)return;let active=true;void(async()=>{try{const token=await auth.getToken();const response=await fetch(`/api/certificates/${encodeURIComponent(certificateId)}`,{headers:token?{Authorization:`Bearer ${token}`}:{}});const data=await response.json();if(!response.ok)throw new Error(data.error??"Certificate not found");if(active)setCertificate(data.certificate as IssuedCertificate);}catch(reason){if(active)setError(reason instanceof Error?reason.message:"Unable to load certificate");}})();return()=>{active=false};},[auth,certificateId]);
  if(!certificate)return <MemberShell title="Certificate"><div className="member-content certificates-list"><p>{error||"Loading certificate…"}</p><Link href="/certificates">Back to certificates</Link></div></MemberShell>;
  return <LoadedCertificateDetail initialCertificate={certificate}/>;
}

function LoadedCertificateDetail({ initialCertificate }: { initialCertificate: IssuedCertificate }) {
  const router=useRouter(); const auth=useAuth(); const [certificate,setCertificate]=useState(initialCertificate); const [name,setName]=useState(certificate.learnerName); const [editing,setEditing]=useState(false); const [savingName,setSavingName]=useState(false); const [downloading,setDownloading]=useState(false); const [copied,setCopied]=useState(false); const [toast,setToast]=useState("");
  const getShareUrl=()=>`${window.location.origin}/verify/${certificate.credentialId}`;
  const share = async () => { const url=getShareUrl(); if(navigator.share) await navigator.share({title:`${certificate.courseTitle} certificate`,text:`I completed ${certificate.courseTitle} with Coursiv!`,url}); else {await navigator.clipboard.writeText(url);setToast("Certificate link copied")}};
  const openSocial=(network:"linkedin"|"facebook")=>{const url=encodeURIComponent(getShareUrl());const text=encodeURIComponent(`I completed ${certificate.courseTitle} with Coursiv!`);window.open(network==="linkedin"?`https://www.linkedin.com/sharing/share-offsite/?url=${url}`:`https://www.facebook.com/sharer/sharer.php?u=${url}&quote=${text}`,"_blank","noopener,noreferrer")};
  const copyAiPost=async()=>{const post=`I’ve completed ${certificate.courseTitle} with Coursiv — ${certificate.courseHours} hours of practical learning, exercises, and review. My verified credential: ${getShareUrl()} #AILearning #ProfessionalDevelopment`;await navigator.clipboard.writeText(post);setToast("Achievement post copied — ready to personalize and share")};
  const saveName=async()=>{setSavingName(true);try{const token=await auth.getToken();const response=await fetch(`/api/certificates/${encodeURIComponent(certificate.id)}`,{method:"PATCH",headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({learnerName:name})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Unable to save name");setCertificate(data.certificate as IssuedCertificate);setEditing(false);setToast("Certificate name updated")}catch(reason){setToast(reason instanceof Error?reason.message:"Unable to save name")}finally{setSavingName(false)}};
  const downloadPdf=async()=>{setDownloading(true);setToast("");try{const token=await auth.getToken();const response=await fetch(`/api/certificates/${encodeURIComponent(certificate.id)}/pdf`,{headers:token?{Authorization:`Bearer ${token}`}:{}});if(!response.ok){const data=await response.json().catch(()=>null);throw new Error(data?.error??"Unable to download certificate");}const url=URL.createObjectURL(await response.blob());const anchor=document.createElement("a");anchor.href=url;anchor.download=`Coursiv-${certificate.courseId}-certificate.pdf`;document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url);setToast("Certificate downloaded")}catch(reason){setToast(reason instanceof Error?reason.message:"Unable to download certificate")}finally{setDownloading(false)}};
  return <MemberShell showTop={false} hideNav><header className="subpage-header certificate-header"><button onClick={()=>router.back()}><ArrowLeft/></button><h1>Your certificate</h1><span/></header><div className="member-content certificate-detail"><span className="cert-eyebrow">CERTIFICATE OF COMPLETION</span><h1>{certificate.courseTitle}</h1><p>The bearer of this certificate has completed the {certificate.courseTitle} course, equivalent to {certificate.courseHours} hours or more of learning.</p><div className="credential-row"><span><BadgeCheck/>Credentials Verified</span><b>{certificate.credentialId}</b></div><CertificateArtwork certificate={certificate} name={name}/>{auth.user?.id===certificate.userId&&(editing?<div className="edit-certificate-name"><input value={name} onChange={(e)=>setName(e.target.value)} autoFocus/><button disabled={savingName} onClick={()=>void saveName()}><Check/>{savingName?"Saving…":"Save name"}</button></div>:<button className="edit-name-button" onClick={()=>setEditing(true)}><Pencil/>Edit name</button>)}<button className="download-certificate" disabled={downloading} onClick={()=>void downloadPdf()}><Download/>{downloading?"Preparing PDF…":"Download PDF"}</button><div className="certificate-share-grid"><button onClick={copyAiPost}><span><Sparkles/></span>Post copy</button><button onClick={()=>openSocial("linkedin")}><span><b>in</b></span>LinkedIn</button><button onClick={()=>openSocial("facebook")}><span><b>f</b></span>Facebook</button><button onClick={async()=>{await navigator.clipboard.writeText(getShareUrl());setCopied(true);setToast("Certificate link copied")}}><span>{copied?<Check/>:<Copy/>}</span>Link</button><button onClick={share}><span><MoreHorizontal/></span>Other</button></div><span className="cert-section-label">ISSUED TO</span><Link href={`/verify/${certificate.credentialId}`} className="issued-to-card"><i>{name.slice(0,2).toUpperCase()}</i><strong>{name}</strong><ChevronRight/></Link><h2>Continue learning</h2><Link href="/course/claude-deep" className="profile-course"><PlaceholderArt label="Claude"/><span><small>RECOMMENDED</small><strong>Claude: Deep Dive</strong><em>13 lessons · 5 hours</em></span><ChevronRight/></Link>{toast&&<div className="certificate-toast" role="status">{toast}</div>}</div></MemberShell>;
}

export function PublicVerificationPage({ certificate }: { certificate: IssuedCertificate }) {
  const date=useMemo(()=>new Date(certificate.issuedAt).toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"}),[certificate.issuedAt]);const [shared,setShared]=useState(false);
  const share=async()=>{if(navigator.share)await navigator.share({title:"Coursiv certificate",url:window.location.href});else await navigator.clipboard.writeText(window.location.href);setShared(true)};
  return <main className="verify-stage"><header><Link href="/dashboard"><span>L</span>Coursiv</Link><b><BadgeCheck/>Verified credential</b></header><section><div className="verify-copy"><span>CERTIFICATE VERIFICATION</span><h1>{certificate.learnerName} completed {certificate.courseTitle}</h1><p>This Coursiv credential confirms successful completion of {certificate.courseHours} hours of guided learning and practical exercises.</p><dl><div><dt>Credential ID</dt><dd>{certificate.credentialId}</dd></div><div><dt>Issued</dt><dd>{date}</dd></div><div><dt>Status</dt><dd><BadgeCheck/>Valid</dd></div></dl><button onClick={()=>void share()}><Share2/>{shared?"Link copied":"Share achievement"}</button></div><CertificateArtwork certificate={certificate}/></section><footer>© 2026 Coursiv · Credential records are protected against client-side modification.</footer></main>;
}
