import Link from "next/link";

const documents:Record<string,{title:string;sections:{heading:string;body:string}[]}>= {
  terms:{title:"Terms and Conditions",sections:[{heading:"Using Coursiv",body:"Use Coursiv for lawful learning activities. Keep your account secure and do not interfere with the service or other learners."},{heading:"Learning content",body:"Coursiv content is educational and does not replace professional legal, financial, medical, or employment advice."},{heading:"Account access",body:"You are responsible for activity on your account. Contact support if you believe access has been compromised."}]},
  subscription:{title:"Subscription Terms",sections:[{heading:"Billing",body:"The price and billing period are shown before checkout. Stripe processes payments and provides billing receipts."},{heading:"Managing a subscription",body:"You can view invoices, update payment details, or cancel through Settings → Manage Subscription."},{heading:"Access after cancellation",body:"Paid access continues until the end of the current billing period unless applicable law requires otherwise."}]},
  privacy:{title:"Privacy Policy",sections:[{heading:"Data we store",body:"Coursiv stores account details, learning progress, preferences, support requests, subscription status, and limited first-touch campaign attribution needed to provide and measure the service."},{heading:"Meta advertising measurement",body:"Where your consent and region allow it, we use Meta Pixel and Meta Conversions API to measure PageView, quiz start, lead, registration, checkout, and first paid purchase events. Browser and server events share an event ID for deduplication. We never send questionnaire answers, lesson content, certificate data, support messages, or raw payment details to Meta."},{heading:"Matching and retention",body:"Email used for server-side advertising matching is normalized and SHA-256 hashed before delivery. Marketing consent is remembered for up to 180 days. Campaign attribution and event delivery records are retained only as needed for measurement, security, retry, and audit purposes."},{heading:"Payments",body:"Stripe processes checkout and payment details. A verified Stripe webhook is the only source used to report a paid Purchase conversion; renewals are not reported as new advertising purchases."},{heading:"Your choices",body:"Visitors in the EEA, United Kingdom, and Switzerland must opt in before marketing tools load. Unknown regions are treated the same way. Other visitors receive notice and can opt out. Use the Privacy choices control at any time to withdraw or grant consent, or request account deletion from Settings."}]},
};

export default async function LegalPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const document=documents[slug];if(!document)return <main className="legal-page"><h1>Document not found</h1><Link href="/profile/settings">Back to Settings</Link></main>;return <main className="legal-page"><Link href="/profile/settings">← Settings</Link><h1>{document.title}</h1><p>Last updated: 2 August 2026</p>{document.sections.map((section)=><section key={section.heading}><h2>{section.heading}</h2><p>{section.body}</p></section>)}</main>}
