"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, BookOpen, ChevronRight, CircleDollarSign, CreditCard, FileBadge, Gauge, History, Images, Inbox, LayoutDashboard, Mail, Menu, MoreHorizontal, Route, Search, Settings, ShieldCheck, TrendingUp, Users, X } from "lucide-react";
import { aiMasteryCourses, allCourseLessons } from "@/lib/member-data";
import { demoOverview, demoSubscriptions, demoUsers } from "@/lib/platform/admin-demo-data";
import { demoCertificates } from "@/lib/certificates";
import type { StaffRole } from "@/lib/platform/types";

const nav = [
  ["Overview", "/admin", LayoutDashboard, ["admin","editor","support","analyst"]], ["Users", "/admin/users", Users, ["admin","support","analyst"]], ["Tickets", "/admin/tickets", Inbox, ["admin","support","analyst"]], ["Payments", "/admin/payments", CreditCard, ["admin","support","analyst"]], ["Certificates", "/admin/certificates", FileBadge, ["admin","support","analyst"]], ["Content", "/admin/content", BookOpen, ["admin","editor","analyst"]], ["Onboarding", "/admin/onboarding", Route, ["admin","editor","analyst"]], ["Media Library", "/admin/media", Images, ["admin","editor"]], ["Time Machine", "/admin/time-machine", History, ["admin"]], ["Staff", "/admin/staff", ShieldCheck, ["admin"]],
] as const;

export function AdminShell({ children, title, subtitle }: { children: React.ReactNode; title: string; subtitle: string }) {
  const pathname = usePathname(); const [open, setOpen] = useState(false);const [role,setRole]=useState<StaffRole>("analyst");
  useEffect(()=>{let active=true;fetch("/api/admin/session",{cache:"no-store"}).then((response)=>response.json()).then((data)=>{if(active&&data.actor?.role)setRole(data.actor.role)});return()=>{active=false}},[]);
  return <div className="admin-stage"><aside className={open ? "open" : ""}><div className="admin-brand"><span>C</span><strong>Coursiv Admin</strong><button onClick={() => setOpen(false)}><X /></button></div><nav>{nav.filter(([, , , roles])=>(roles as readonly StaffRole[]).includes(role)).map(([label, href, Icon]) => <Link className={pathname === href ? "active" : ""} href={href} key={href} onClick={() => setOpen(false)}><Icon />{label}</Link>)}</nav><div className="admin-user"><span>{role.slice(0,2).toUpperCase()}</span><div><strong>Staff workspace</strong><small>{role} access</small></div><Settings /></div></aside>{open && <button className="admin-scrim" onClick={() => setOpen(false)} aria-label="Close menu" />}<main><header><button onClick={() => setOpen(true)}><Menu /></button><div><h1>{title}</h1><p>{subtitle}</p></div><span className="admin-live"><i /> Secure workspace</span></header><div className="admin-content">{children}</div></main></div>;
}

function Metric({ label, value, note, icon: Icon, tone = "purple" }: { label: string; value: string; note: string; icon: typeof Users; tone?: string }) { return <article className="admin-metric"><span className={tone}><Icon /></span><div><small>{label}</small><strong>{value}</strong><em>{note}</em></div></article>; }

export function AdminOverviewPage() {
  type Snapshot = typeof demoOverview & { totalUsers:number;certificateCount:number;openTickets:number;lessonsCompleted:number;content:{courses:number;lessons:number;screens:number};recentSubscriptions:typeof demoSubscriptions;generatedAt:string };
  const [snapshot,setSnapshot]=useState<Snapshot|null>(null);
  const [error,setError]=useState("");
  useEffect(()=>{let active=true;fetch("/api/admin/overview").then(async(response)=>{const data=await response.json();if(!response.ok)throw new Error(data.error??"Unable to load dashboard");if(active)setSnapshot(data)}).catch((reason)=>{if(active)setError(reason instanceof Error?reason.message:"Unable to load dashboard")});return()=>{active=false}},[]);
  const data=snapshot??{...demoOverview,totalUsers:0,certificateCount:0,openTickets:0,lessonsCompleted:0,content:{courses:0,lessons:0,screens:0},recentSubscriptions:[],generatedAt:""};
  return <AdminShell title="Overview" subtitle="Live members, billing, support and content health">
    {error&&<p className="cms-message">{error}</p>}
    <div className="admin-metrics"><Metric label="Active members" value={data.activeMembers.toLocaleString()} note={`${data.totalUsers.toLocaleString()} registered users`} icon={Users}/><Metric label="Monthly recurring revenue" value={`$${data.monthlyRecurringRevenue.toLocaleString()}`} note="Stripe-synchronised estimate" icon={CircleDollarSign} tone="green"/><Metric label="Trial members" value={String(data.trialMembers)} note={`${data.openTickets} open support tickets`} icon={TrendingUp} tone="blue"/><Metric label="Failed payments" value={String(data.failedPayments)} note="Past due or unpaid" icon={AlertTriangle} tone="red"/></div>
    <div className="admin-grid"><section className="admin-panel"><div className="admin-panel-title"><div><h2>Operational health</h2><p>Current Firestore projections</p></div><Activity/></div><div className="conversion-list"><div><strong>{data.lessonsCompleted.toLocaleString()}</strong><span>Lessons completed</span></div><div><strong>{data.certificateCount.toLocaleString()}</strong><span>Certificates achieved</span></div><div><strong>{data.openTickets.toLocaleString()}</strong><span>Tickets requiring action</span></div></div></section><section className="admin-panel"><div className="admin-panel-title"><div><h2>Content source</h2><p>Published canonical corpus</p></div><Gauge /></div><div className="conversion-list"><div><strong>{data.content.courses}</strong><span>Courses</span></div><div><strong>{data.content.lessons}</strong><span>Lessons</span></div><div><strong>{data.content.screens.toLocaleString()}</strong><span>Screens</span></div></div></section></div>
    <section className="admin-panel"><div className="admin-panel-title"><div><h2>Recent payment activity</h2><p>Stripe webhook subscription records</p></div><Link href="/admin/payments">View all <ChevronRight /></Link></div><div className="admin-table-wrap"><table><thead><tr><th>Subscription</th><th>User</th><th>Status</th><th>Renewal</th></tr></thead><tbody>{data.recentSubscriptions.length?data.recentSubscriptions.map((subscription)=><tr key={subscription.id}><td><b>{subscription.stripeSubscriptionId}</b><small>{subscription.priceId}</small></td><td>{subscription.userId}</td><td><em className={`status ${subscription.status}`}>{subscription.status.replaceAll("_"," ")}</em></td><td>{subscription.currentPeriodEnd??"—"}</td></tr>):<tr><td colSpan={4}>{snapshot?"No subscription records yet.":"Loading dashboard…"}</td></tr>}</tbody></table></div></section>
  </AdminShell>;
}

export function AdminUsersPage() {
  const [query,setQuery]=useState(""); const filtered=useMemo(()=>demoUsers.filter((x)=>`${x.displayName} ${x.email}`.toLowerCase().includes(query.toLowerCase())),[query]);
  return <AdminShell title="Users" subtitle="Members, roles and learning activity"><div className="admin-toolbar"><label><Search/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search users"/></label><button>Export CSV</button></div><section className="admin-panel admin-table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Onboarding</th><th>Last active</th><th /></tr></thead><tbody>{filtered.map((user)=><tr key={user.id}><td><span className="table-user"><i>{user.displayName.slice(0,2).toUpperCase()}</i><b>{user.displayName}<small>{user.email}</small></b></span></td><td><em className={`status ${user.role}`}>{user.role}</em></td><td>{user.onboardingCompleted?"Complete":"Incomplete"}</td><td>{new Date(user.lastActiveAt).toLocaleString("en-HK",{dateStyle:"medium",timeStyle:"short"})}</td><td><button><MoreHorizontal/></button></td></tr>)}</tbody></table></section></AdminShell>;
}

function PaymentTable({ compact=false }: { compact?:boolean }) { const rows=compact?demoSubscriptions.slice(0,3):demoSubscriptions; return <div className="admin-table-wrap"><table><thead><tr><th>Subscription</th><th>User</th><th>Status</th><th>Renewal</th><th /></tr></thead><tbody>{rows.map((sub)=><tr key={sub.id}><td><b>{sub.stripeSubscriptionId}</b><small>{sub.priceId}</small></td><td>{demoUsers.find((x)=>x.id===sub.userId)?.email}</td><td><em className={`status ${sub.status}`}>{sub.status.replace("_"," ")}</em></td><td>{sub.currentPeriodEnd??"—"}</td><td><button><MoreHorizontal/></button></td></tr>)}</tbody></table></div>; }

export function AdminPaymentsPage() { return <AdminShell title="Payments" subtitle="Subscriptions, revenue and payment recovery"><div className="admin-metrics"><Metric label="MRR" value={`$${demoOverview.monthlyRecurringRevenue.toLocaleString()}`} note="Recurring revenue" icon={CircleDollarSign} tone="green"/><Metric label="Active" value={String(demoOverview.activeMembers)} note="Paid access" icon={Activity}/><Metric label="Past due" value={String(demoOverview.failedPayments)} note="Retry required" icon={AlertTriangle} tone="red"/></div><section className="admin-panel"><div className="admin-panel-title"><div><h2>Subscriptions</h2><p>Webhook-synchronised billing status</p></div><button>Export</button></div><PaymentTable /></section></AdminShell>; }

export function AdminCertificatesPage() {
  const [form,setForm]=useState({learnerName:"HJ",recipientEmail:"hj@lumora.demo",courseId:"chatgpt",courseTitle:"ChatGPT",courseHours:6}); const [result,setResult]=useState(""); const [busy,setBusy]=useState(false);
  const issue=async()=>{setBusy(true);setResult("");try{const response=await fetch("/api/certificates/issue",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const data=await response.json();setResult(response.ok?`Issued ${data.certificate.credentialId} · Email ${data.delivery.status}`:data.error)}catch{setResult("Unable to issue certificate")}finally{setBusy(false)}};
  return <AdminShell title="Certificates" subtitle="Issue, email and verify learner credentials"><div className="admin-metrics"><Metric label="Issued certificates" value={String(demoCertificates.length)} note="Demo records" icon={FileBadge}/><Metric label="Emails delivered" value={String(demoCertificates.filter((x)=>x.emailStatus==="sent").length)} note="Completion notifications" icon={Mail} tone="green"/></div><div className="admin-grid certificate-admin-grid"><section className="admin-panel"><div className="admin-panel-title"><div><h2>Issue certificate</h2><p>Production issuance is triggered by course completion</p></div></div><div className="issue-form"><label>Learner name<input value={form.learnerName} onChange={(e)=>setForm({...form,learnerName:e.target.value})}/></label><label>Recipient email<input value={form.recipientEmail} onChange={(e)=>setForm({...form,recipientEmail:e.target.value})}/></label><label>Course<select value={form.courseId} onChange={(e)=>{const title=e.target.options[e.target.selectedIndex].text;setForm({...form,courseId:e.target.value,courseTitle:title})}}><option value="chatgpt">ChatGPT</option><option value="claude">Claude</option><option value="jasper">Jasper AI</option></select></label><label>Course hours<input type="number" min="1" value={form.courseHours} onChange={(e)=>setForm({...form,courseHours:Number(e.target.value)})}/></label><button onClick={issue} disabled={busy}>{busy?"Issuing…":"Issue & send email"}</button>{result&&<p className="issue-result">{result}</p>}</div></section><section className="admin-panel"><div className="admin-panel-title"><div><h2>Email preview</h2><p>Completion-to-sharing lifecycle message</p></div><a href="/email-preview/certificate" target="_blank">Open preview</a></div><div className="email-mini-preview"><span>Lumora</span><div><strong>Your certificate is ready</strong><p>Celebrate the win and share your verified credential.</p><button>View & Share Certificate</button></div></div></section></div><section className="admin-panel"><div className="admin-panel-title"><div><h2>Issued credentials</h2><p>Certificate and email delivery status</p></div></div><div className="admin-table-wrap"><table><thead><tr><th>Learner</th><th>Course</th><th>Credential</th><th>Email</th><th>Issued</th></tr></thead><tbody>{demoCertificates.map((cert)=><tr key={cert.id}><td>{cert.learnerName}<small>{cert.recipientEmail}</small></td><td>{cert.courseTitle}</td><td><a href={`/verify/${cert.credentialId}`} target="_blank">{cert.credentialId}</a></td><td><em className={`status ${cert.emailStatus}`}>{cert.emailStatus.replace("_"," ")}</em></td><td>{new Date(cert.issuedAt).toLocaleDateString("en-GB")}</td></tr>)}</tbody></table></div></section></AdminShell>;
}

export function AdminContentPage() {
  const [selected,setSelected]=useState<string|null>(null);
  return <AdminShell title="Content" subtitle="Programs, courses and lesson publishing"><div className="content-summary"><span><BookOpen/><b>5<small>Courses</small></b></span><span><Activity/><b>54<small>Lessons</small></b></span><span><AlertTriangle/><b>53<small>Placeholders</small></b></span></div><section className="admin-panel"><div className="admin-panel-title"><div><h2>AI Mastery Certificate Program</h2><p>Published program · updated today</p></div><button>Program settings</button></div><div className="admin-course-list">{aiMasteryCourses.map((course,index)=><article key={course.id}><i style={{background:course.color}}>{course.title.slice(0,2)}</i><div><strong>{course.title}</strong><small>{allCourseLessons(course).length} lessons · {course.duration}</small><span><b style={{width:index===0?"8%":"0%"}}/></span></div><em className={`status ${index===0?"published":"draft"}`}>{index===0?"Published":"Draft"}</em><button onClick={()=>setSelected(course.id)}>Manage <ChevronRight/></button></article>)}</div></section>{selected&&<div className="admin-drawer-scrim" onMouseDown={(e)=>e.target===e.currentTarget&&setSelected(null)}><aside className="content-drawer"><button onClick={()=>setSelected(null)}><X/></button><span>COURSE EDITOR</span><h2>{aiMasteryCourses.find((x)=>x.id===selected)?.title}</h2><p>The CMS editor will write course metadata and lesson screens to Firestore. Until Firebase credentials are connected, changes stay disabled.</p><label>Course title<input value={aiMasteryCourses.find((x)=>x.id===selected)?.title} readOnly/></label><label>Publishing status<select defaultValue={selected==="chatgpt"?"published":"draft"} disabled><option>draft</option><option>published</option></select></label><button disabled>Save changes</button></aside></div>}</AdminShell>;
}
