"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Ban, BadgeCheck, BookOpen, CalendarDays, ChevronRight, CreditCard, FileText, Filter, History, MessageCircle, RotateCcw, Search, Tag, UserRoundCheck, X } from "lucide-react";
import { AdminShell } from "./admin-pages";
import { AdminActionModal, type AdminActionDialog } from "./admin-action-modal";
import type { AdminUserSummary, IssuedCertificate, SubscriptionRecord, SubscriptionStatus, SupportTicket } from "@/lib/platform/types";

type Detail={summary:AdminUserSummary;subscription:SubscriptionRecord|null;certificates:IssuedCertificate[];tickets:SupportTicket[];events:Array<Record<string,unknown>>;meta:{tags?:string[];internalNotes?:Array<{id:string;text:string;createdAt:string;createdBy:string}>};progress?:Array<Record<string,unknown>>};
const tabs=["Overview","Learning","Billing","Certificates","Tickets","Activity","Internal Notes"] as const;
const csvCell=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;
const friendlyLabel=(value:unknown,fallback:string)=>{
  const text=String(value??"").trim();
  if(!text)return fallback;
  return text.replaceAll("_"," ").replaceAll("-"," ").replace(/\b\w/g,(character)=>character.toUpperCase());
};
const friendlyDate=(value:unknown)=>{
  if(!value)return "Date unavailable";
  const date=new Date(String(value));
  return Number.isNaN(date.getTime())?"Date unavailable":date.toLocaleString();
};

export function UserCrmPage(){
  const [users,setUsers]=useState<AdminUserSummary[]>([]);const [query,setQuery]=useState("");const [subscriptionFilter,setSubscriptionFilter]=useState<SubscriptionStatus|"all">("all");const [accountFilter,setAccountFilter]=useState<AdminUserSummary["accountStatus"]|"all">("all");const [registrationWindow,setRegistrationWindow]=useState("all");const [tagFilter,setTagFilter]=useState("");const [selected,setSelected]=useState<string|null>(null);const [detail,setDetail]=useState<Detail|null>(null);const [tab,setTab]=useState<typeof tabs[number]>("Overview");const [message,setMessage]=useState("");const [actionDialog,setActionDialog]=useState<AdminActionDialog|null>(null);const [nextCursor,setNextCursor]=useState<string|null>(null);const [listBusy,setListBusy]=useState(false);
  const registeredFrom=useMemo(()=>{if(registrationWindow==="all")return"";const days=Number(registrationWindow);const date=new Date();date.setUTCDate(date.getUTCDate()-days);return date.toISOString().slice(0,10)},[registrationWindow]);
  const listUrl=useCallback((cursor?:string|null)=>{const params=new URLSearchParams({q:query.trim(),subscription:subscriptionFilter,account:accountFilter,registeredFrom,tag:tagFilter.trim()});if(cursor)params.set("cursor",cursor);return`/api/admin/users?${params}`},[accountFilter,query,registeredFrom,subscriptionFilter,tagFilter]);
  const filtersActive=Boolean(query.trim()||subscriptionFilter!=="all"||accountFilter!=="all"||registrationWindow!=="all"||tagFilter.trim());
  const clearFilters=()=>{setQuery("");setSubscriptionFilter("all");setAccountFilter("all");setRegistrationWindow("all");setTagFilter("")};
  useEffect(()=>{let active=true;const controller=new AbortController();const timer=setTimeout(()=>{setListBusy(true);setMessage("");fetch(listUrl(),{signal:controller.signal}).then((r)=>r.json()).then((data)=>{if(!active)return;setUsers(data.users??[]);setNextCursor(data.nextCursor??null);if(data.error)setMessage(data.error)}).catch((error)=>{if(active&&error instanceof Error&&error.name!=="AbortError")setMessage("Unable to load users.")}).finally(()=>{if(active)setListBusy(false)})},250);return()=>{active=false;clearTimeout(timer);controller.abort()}},[listUrl]);
  useEffect(()=>{if(!selected)return;let active=true;fetch(`/api/admin/users/${encodeURIComponent(selected)}`).then((r)=>r.json()).then((data)=>{if(!active)return;setDetail(data.summary?data:null)});return()=>{active=false}},[selected]);
  useEffect(()=>{const requested=new URLSearchParams(window.location.search).get("user");if(!requested)return;const timer=window.setTimeout(()=>{setDetail(null);setTab("Overview");setSelected(requested)},0);return()=>window.clearTimeout(timer)},[]);
  const stats=useMemo(()=>({paid:users.filter((user)=>["active","trialing"].includes(user.subscriptionStatus)).length,certificates:users.reduce((sum,user)=>sum+user.certificateCount,0),tickets:users.reduce((sum,user)=>sum+user.openTicketCount,0)}),[users]);
  const loadMore=async()=>{if(!nextCursor||listBusy)return;setListBusy(true);try{const data=await fetch(listUrl(nextCursor)).then((result)=>result.json());setUsers((current)=>{const seen=new Set(current.map((item)=>item.id));return [...current,...(data.users??[]).filter((item:AdminUserSummary)=>!seen.has(item.id))]});setNextCursor(data.nextCursor??null)}catch{setMessage("Unable to load more users.")}finally{setListBusy(false)}};
  const openUser=(id:string)=>{setDetail(null);setTab("Overview");setSelected(id)};
  const performAction=async(actionName:"tag"|"note"|"suspend"|"restore"|"reset_course",values:Record<string,string>)=>{if(!detail)return;const response=await fetch(`/api/admin/users/${detail.summary.id}/actions`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({action:actionName,value:values.value,courseId:values.courseId,reason:values.reason,confirm:true})});const data=await response.json();if(!response.ok)throw new Error(data.error??"User action failed");setMessage("User record updated");const refreshed=await fetch(`/api/admin/users/${encodeURIComponent(detail.summary.id)}`).then((result)=>result.json());if(refreshed.summary)setDetail(refreshed)};
  const requestUserAction=(actionName:"tag"|"note"|"suspend"|"restore"|"reset_course")=>{if(!detail)return;const name=detail.summary.displayName;const configurations:Record<typeof actionName,Omit<AdminActionDialog,"key"|"onConfirm">>={
    tag:{title:`Add a tag to ${name}`,description:"Tags help support and operations staff find and group members.",confirmLabel:"Add tag",fields:[{name:"value",label:"Tag name",placeholder:"For example: VIP or billing follow-up",required:true}]},
    note:{title:`Add an internal note`,description:`Only staff can see this note on ${name}’s profile.`,confirmLabel:"Save note",fields:[{name:"value",label:"Internal note",kind:"textarea",placeholder:"Add useful context for the next teammate",required:true}]},
    suspend:{title:`Suspend ${name}?`,description:"The member will be unable to sign in until the account is restored. Billing is not changed.",confirmLabel:"Suspend account",tone:"danger",fields:[{name:"reason",label:"Suspension reason",kind:"textarea",required:true}]},
    restore:{title:`Restore ${name}?`,description:"The member will be allowed to sign in again. Billing is not changed.",confirmLabel:"Restore account",fields:[{name:"reason",label:"Restoration note",kind:"textarea",required:true}]},
    reset_course:{title:`Reset course progress for ${name}?`,description:"Only the selected course progress is removed. Certificates already issued are preserved.",confirmLabel:"Reset course progress",tone:"danger",fields:[{name:"courseId",label:"Course ID",placeholder:"For example: claude",required:true},{name:"reason",label:"Reason for reset",kind:"textarea",required:true}]},
  };const config=configurations[actionName];setActionDialog({...config,key:`${actionName}:${detail.summary.id}`,onConfirm:(values)=>performAction(actionName,values)})};
  return <AdminShell title="User CRM" subtitle="Registration, paid access, learning, certificates and support history">
    <div className="crm-metrics"><span><UserRoundCheck/><b>{users.length}<small>{filtersActive?"Matching users":"Users loaded"}</small></b></span><span><CreditCard/><b>{stats.paid}<small>Paid / trial</small></b></span><span><BadgeCheck/><b>{stats.certificates}<small>Certificates</small></b></span><span><MessageCircle/><b>{stats.tickets}<small>Open tickets</small></b></span></div>
    <section className="crm-filter-panel">
      <div className="admin-toolbar"><label><Search/><input maxLength={80} aria-label="Search users" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search name, email or user ID"/></label><button disabled={!users.length} onClick={()=>{const csv=[["Email","Name","Registered","Paid","Account","Lessons","Certificates","Open tickets","Tags"].map(csvCell).join(","),...users.map((user)=>[user.email,user.displayName,user.registeredAt,user.subscriptionStatus,user.accountStatus,user.completedLessonCount,user.certificateCount,user.openTicketCount,user.tags.join("; ")].map(csvCell).join(","))].join("\n");const url=URL.createObjectURL(new Blob([`\uFEFF${csv}`],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=`coursiv-users-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url)}}>Export filtered users</button></div>
      <div className="crm-filter-row"><span><Filter/>Filters</span><label>Paid status<select aria-label="Filter paid status" value={subscriptionFilter} onChange={(event)=>setSubscriptionFilter(event.target.value as SubscriptionStatus|"all")}><option value="all">All paid statuses</option><option value="active">Active</option><option value="trialing">Trial</option><option value="past_due">Past due</option><option value="canceled">Canceled</option><option value="unpaid">Unpaid</option><option value="none">No subscription</option></select></label><label>Account<select aria-label="Filter account status" value={accountFilter} onChange={(event)=>setAccountFilter(event.target.value as AdminUserSummary["accountStatus"]|"all")}><option value="all">All accounts</option><option value="active">Active</option><option value="suspended">Suspended</option><option value="deleted">Deleted</option></select></label><label>Registration<select aria-label="Filter registration date" value={registrationWindow} onChange={(event)=>setRegistrationWindow(event.target.value)}><option value="all">Any date</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="365">Last year</option></select></label><label>Exact tag<input aria-label="Filter user tag" value={tagFilter} onChange={(event)=>setTagFilter(event.target.value)} placeholder="VIP"/></label>{filtersActive&&<button className="crm-clear-filters" onClick={clearFilters}><RotateCcw/>Clear filters</button>}</div>
      <p><CalendarDays/>{listBusy?"Updating results…":`${users.length} ${users.length===1?"user":"users"} shown${nextCursor?" · more available":""}`}</p>
    </section>
    {message&&<p className="cms-message">{message}</p>}
    <section className="admin-panel admin-table-wrap"><table><thead><tr><th>User</th><th>Registered</th><th>Paid status</th><th>Learning</th><th>Certificates</th><th>Tickets</th><th/></tr></thead><tbody>{users.map((user)=><tr key={user.id}><td><span className="table-user"><i>{user.displayName.slice(0,2).toUpperCase()}</i><b>{user.displayName}<small>{user.email}</small></b></span></td><td>{user.registeredAt?new Date(user.registeredAt).toLocaleDateString():"—"}<small>Last {user.lastActiveAt?new Date(user.lastActiveAt).toLocaleDateString():"—"}</small></td><td><em className={`status ${user.subscriptionStatus}`}>{user.subscriptionStatus.replaceAll("_"," ")}</em></td><td>{user.completedLessonCount} lessons</td><td>{user.certificateCount}</td><td>{user.openTicketCount}</td><td><button onClick={()=>openUser(user.id)}>Open <ChevronRight/></button></td></tr>)}{!users.length&&!listBusy&&<tr><td colSpan={7}><div className="crm-table-empty"><Search/><strong>No users match these filters</strong><small>Try a broader search, another paid status or clear all filters.</small>{filtersActive&&<button onClick={clearFilters}>Clear filters</button>}</div></td></tr>}</tbody></table>{nextCursor&&<button className="admin-load-more" disabled={listBusy} onClick={()=>void loadMore()}>{listBusy?"Loading…":"Load more users"}</button>}{listBusy&&!users.length&&<p className="admin-table-loading">Loading users…</p>}</section>
    {selected&&<div className="admin-drawer-scrim" onMouseDown={(event)=>event.target===event.currentTarget&&setSelected(null)}><aside className="crm-drawer"><button className="crm-close" onClick={()=>setSelected(null)} aria-label="Close user profile"><X/></button>{!detail?<p className="admin-drawer-loading">Loading user profile…</p>:<><header><i>{detail.summary.displayName.slice(0,2).toUpperCase()}</i><div><h2>{detail.summary.displayName}</h2><p>{detail.summary.email}</p><small>Registered {new Date(detail.summary.registeredAt).toLocaleString()}</small></div><em className={`status ${detail.summary.accountStatus}`}>{detail.summary.accountStatus}</em></header><nav>{tabs.map((item)=><button className={tab===item?"active":""} onClick={()=>setTab(item)} key={item}>{item}</button>)}</nav><div className="crm-detail">
      {tab==="Overview"&&<><div className="crm-detail-grid"><span><CreditCard/><b>{detail.summary.subscriptionStatus}</b><small>Paid status</small></span><span><BookOpen/><b>{detail.summary.completedLessonCount}</b><small>Lessons</small></span><span><BadgeCheck/><b>{detail.summary.certificateCount}</b><small>Certificates</small></span><span><MessageCircle/><b>{detail.summary.openTicketCount}</b><small>Open tickets</small></span></div>{detail.summary.tags.length>0&&<div className="crm-tag-row">{detail.summary.tags.map((item)=><span key={item}>{item}</span>)}</div>}<h3>Safe operations</h3><div className="crm-actions"><button onClick={()=>requestUserAction("tag")}><Tag/>Add tag</button><button onClick={()=>requestUserAction("note")}><FileText/>Internal note</button><button onClick={()=>requestUserAction("reset_course")}><RotateCcw/>Reset course</button><button className="danger" onClick={()=>requestUserAction(detail.summary.accountStatus==="suspended"?"restore":"suspend")}><Ban/>{detail.summary.accountStatus==="suspended"?"Restore":"Suspend"}</button></div></>}
      {tab==="Learning"&&<div className="crm-list">{(detail.progress??[]).length?(detail.progress??[]).map((item,index)=><article key={String(item.id??item.lessonId??index)}><BookOpen/><span><strong>{String(item.lessonTitle??item.lessonId??"Lesson")}</strong><small>{String(item.courseTitle??item.courseId??"Course")} · {item.completedAt?"Completed":"In progress"}{item.updatedAt?<><br/>Updated {new Date(String(item.updatedAt)).toLocaleString()}</>:null}</small></span></article>):<div className="crm-friendly-empty"><BookOpen/><strong>No learning activity yet</strong><small>Lesson progress will appear here after the member starts a course.</small></div>}</div>}
      {tab==="Billing"&&<div className="crm-billing-card">{detail.subscription?<><span><small>Status</small><strong>{detail.subscription.status.replaceAll("_"," ")}</strong></span><span><small>Renewal</small><strong>{detail.subscription.currentPeriodEnd?new Date(detail.subscription.currentPeriodEnd).toLocaleDateString():"Not scheduled"}</strong></span><span><small>Cancel at period end</small><strong>{detail.subscription.cancelAtPeriodEnd?"Yes":"No"}</strong></span><span><small>Price</small><strong>{detail.subscription.priceId||"—"}</strong></span><p>Payment changes and refunds continue in Stripe Dashboard.</p></>:<div className="crm-friendly-empty"><CreditCard/><strong>No paid subscription</strong><small>This member does not have a Stripe subscription record.</small></div>}</div>}
      {tab==="Certificates"&&<div className="crm-list">{detail.certificates.length?detail.certificates.map((item)=><article key={item.id}><BadgeCheck/><span><strong>{item.courseTitle}</strong><small>{item.credentialId} · {new Date(item.issuedAt).toLocaleDateString()}</small></span></article>):<div className="crm-friendly-empty"><BadgeCheck/><strong>No certificates yet</strong><small>Issued certificates will appear here with their credential details.</small></div>}</div>}
      {tab==="Tickets"&&<div className="crm-list">{detail.tickets.length?detail.tickets.map((item)=><article key={item.id}><MessageCircle/><span><strong>{item.subject??friendlyLabel(item.type,"Support request")}</strong><small>{friendlyLabel(item.status,"Unknown status")} · {friendlyDate(item.createdAt)}</small></span></article>):<div className="crm-friendly-empty"><MessageCircle/><strong>No support tickets</strong><small>This member has not contacted support yet.</small></div>}</div>}
      {tab==="Activity"&&<div className="crm-list">{detail.events.length?detail.events.map((item,index)=><article key={String(item.id??index)}><History/><span><strong>{friendlyLabel(item.name??item.type,"Member activity")}</strong><small>{friendlyDate(item.occurredAt??item.createdAt)}</small></span></article>):<div className="crm-friendly-empty"><History/><strong>No recorded activity yet</strong><small>Sign-ins, learning milestones and billing events will appear here.</small></div>}</div>}
      {tab==="Internal Notes"&&<div className="crm-list">{detail.meta.internalNotes?.map((item)=><article key={item.id}><FileText/><span><strong>{item.text}</strong><small>{new Date(item.createdAt).toLocaleString()} · {item.createdBy}</small></span></article>)}<button onClick={()=>requestUserAction("note")}>Add internal note</button></div>}
    </div></>}</aside></div>}
    {actionDialog&&<AdminActionModal key={actionDialog.key} dialog={actionDialog} onClose={()=>setActionDialog(null)}/>}
  </AdminShell>
}
