export const AI_WORKDAY_MIGRATION_ID = "ai-workday-v1";

export const onboardingCopy = [
  { id:"01-dynamic", title:"Build Your Personal AI Workday Plan", subtitle:"Discover where AI can save you time and give you more control over your workday.", options:["I work for a company","I manage a team","I run a business","I freelance or work independently","I’m preparing for a new role"] },
  { id:"02-classic-social-proof", title:"Built for Busy Professionals", subtitle:"Short, practical lessons designed around work you already do—no technical background required." },
  { id:"03-question-page", title:"Where does most of your workday happen?", subtitle:"We’ll adapt your plan to how you work.", options:["At a company","Across a team I manage","In my own business","As a freelancer or independent worker","While preparing for a new role"] },
  { id:"04-question-page-2", title:"What would make the biggest difference to your workday?", subtitle:"Choose the result that matters most right now.", options:["Finish work with less stress","Save time on repetitive tasks","Communicate more clearly","Make better decisions","Create more time for important work"] },
  { id:"05-question-page-3", title:"Which type of work do you do most often?", subtitle:"Your answer helps us recommend relevant workflows.", options:["Email and communication","Meetings and coordination","Documents and reports","Research and analysis","Spreadsheets and data","Sales and customer work","Planning and management"] },
  { id:"06-question-page-4", title:"How does your workday usually feel?", subtitle:"Be honest—there’s no right answer.", options:["Constantly reacting","Busy but not progressing","Frequently distracted","Overwhelmed by too many priorities","Mostly in control"] },
  { id:"07-question-page-5", title:"How much control do you have over your daily priorities?", subtitle:"This helps us understand your current work system.", options:["Messages and requests control my day","I make a plan but rarely follow it","I know my priorities but struggle to start","I work well but take on too much","I control most of my schedule"] },
  { id:"08-wild-page", title:"Being Busy Isn’t the Same as Moving Forward", subtitle:"The right workflow reduces reactive work and protects time for what matters." },
  { id:"09-question-page-6", title:"What consumes the most unnecessary time?", subtitle:"We’ll target your biggest workday leak first.", options:["Email","Meetings","Searching for information","Writing documents","Manual data entry","Switching between tasks","Deciding what to do next"] },
  { id:"10-question-page-7", title:"How much experience do you have using AI for work?", subtitle:"Your plan will start at the right level.", options:["I haven’t used AI for work","I’ve tried a few simple prompts","I use AI occasionally","I use AI regularly","I’ve built repeatable AI workflows"] },
  { id:"11-question-page-8", title:"What stops you from using AI more effectively?", subtitle:"We’ll build around your biggest barrier.", options:["I don’t know what to use it for","I don’t trust the answers","I’m worried about privacy","Prompting feels complicated","I don’t have time to learn","I’ve tried, but the results weren’t useful"] },
  { id:"12-question-page-9", title:"Which best describes your role?", subtitle:"Different roles need different workflows.", options:["Individual contributor","Manager","Team leader","Executive","Business owner","Freelancer","Job seeker"] },
  { id:"13-question-page-10", title:"Which workflow would you improve first?", subtitle:"Choose one result for your first week.", options:["Write and reply to emails","Turn meetings into action lists","Research and summarize information","Create reports and documents","Understand spreadsheets","Plan and prioritize work","Automate repeated admin"] },
  { id:"14-question-page-11", title:"What concerns you most about AI at work?", subtitle:"Your plan will address this concern directly.", options:["Falling behind colleagues","Producing inaccurate work","Exposing confidential information","My role changing too quickly","Becoming dependent on AI","I see AI mainly as an opportunity"] },
  { id:"15-wild-page-2", title:"AI Should Fit Your Workday—Not Add Another Tool", subtitle:"You’ll learn workflows based on outcomes, not random features." },
  { id:"16-question-page-12", title:"Have you tried productivity systems or AI courses before?", subtitle:"This helps us avoid repeating what hasn’t worked.", options:["This is my first structured program","I’ve watched free videos","I’ve bought a productivity course","I’ve tried task-management systems","I already use AI but lack a clear workflow"] },
  { id:"17-question-page-13", title:"How do you prefer to learn?", subtitle:"We’ll adapt the balance of lessons, examples and practice.", options:["Step-by-step examples","Short explanations","Interactive practice","Templates and checklists","A mixture of everything"] },
  { id:"18-question-page-14", title:"What would feel like a meaningful win this week?", subtitle:"Your first milestone should be small, useful and achievable.", options:["Clear my email backlog","Improve one recurring meeting","Finish a document faster","Save a reusable workflow","Regain one focused hour","Feel more confident using AI"] },
  { id:"19-question-page-15", title:"How much time can you invest each day?", subtitle:"Consistency matters more than long sessions.", options:["5 minutes","10 minutes","15 minutes","20 minutes"] },
  { id:"20-question-page-16", title:"What would you do with more control over your time?", subtitle:"Connect your plan to something personally meaningful.", options:["Finish work earlier","Spend more time with family","Focus on strategic work","Learn new skills","Build a side project","Feel less stressed"] },
  { id:"21-followup-teaser-page", title:"Your Workday Profile Is Taking Shape", subtitle:"We’ve identified the patterns behind your answers." },
  { id:"22-magic-page", title:"Building Your Personal AI Workday Plan", subtitle:"Matching your role, time drains, experience and goals to the right workflows.", description:"Analyzing your workday patterns…" },
  { id:"23-email-page", title:"Where should we send your plan?", subtitle:"Enter your email to save your results and continue on any device. Product updates and offers are optional." },
  { id:"24-enter-name-page", title:"What should we call you?", subtitle:"We’ll use your name inside your personal plan." },
  { id:"25-personalized-summary-page", title:"Your AI Workday Profile", subtitle:"See your biggest workday leak, strongest opportunity and recommended starting point." },
  { id:"26-before-after-page-personalized", title:"From Reactive to In Control", subtitle:"Your plan turns repetitive work into clear, reusable workflows." },
  { id:"27-solution-pitch-page", title:"A System Built Around Work You Already Do", subtitle:"Learn one practical workflow at a time and apply it immediately." },
  { id:"28-social-proof-testimonials-page", title:"What Your First Week Will Produce", subtitle:"Preview the emails, meeting actions, documents and time-saving workflows you’ll create." },
  { id:"29-selling-page", title:"Your AI Workday Plan Is Ready", subtitle:"Start with short daily lessons and build a practical system for your role." },
];

const lesson = (title, objective, practice) => ({ title, objective, practice });

export const aiWorkdayCourses = [
  {
    id:"ai-workday-reset", title:"AI Workday Reset", status:"published", duration:"45 min", categories:["AI Workday","Start Here","Productivity"],
    description:"Identify where your time goes, choose one meaningful priority and build a simple daily system that protects your attention.",
    lessons:[
      lesson("Why Your Workday Feels Out of Control","Separate reactive activity from deliberate progress so you can see what is actually driving the day.","Label yesterday’s work as reactive, routine or progress-making."),
      lesson("Audit Your Real Workday","Capture a truthful picture of where time and attention go before choosing a solution.","Complete a one-day time and interruption audit."),
      lesson("Find Your Highest-Value Work","Identify the work that creates meaningful results instead of treating every task as equally important.","Choose one weekly outcome and define what finished looks like."),
      lesson("Remove Low-Value Commitments","Use elimination, simplification and boundaries before adding another productivity tool.","Create a stop-doing list with one commitment to remove this week."),
      lesson("Design Your Ideal Workday","Place focused, collaborative and administrative work where each fits best.","Draft a realistic ideal-day calendar with protected focus and communication windows."),
      lesson("Complete Your First Weekly Reset","Review evidence, close loose ends and choose next week’s most important outcome.","Run a 15-minute weekly reset and save the checklist."),
    ],
  },
  {
    id:"ai-email-communication", title:"AI Email & Communication", status:"published", duration:"55 min", categories:["AI Workday","Communication"],
    description:"Use AI to draft, improve and organize workplace communication without losing your judgment, tone or privacy.",
    lessons:[
      lesson("Decide What AI Should and Shouldn’t Write","Distinguish low-risk drafting support from messages that require direct human judgment.","Sort five common messages by AI-safe, review carefully or human-only."),
      lesson("Turn Rough Notes Into a Clear Email","Give AI the audience, purpose, facts and desired action needed for a useful draft.","Turn bullet notes into a concise email with one clear request."),
      lesson("Write Difficult Messages Professionally","Structure sensitive workplace messages without becoming vague, aggressive or emotionally reactive.","Draft a boundary-setting message and review its tone."),
      lesson("Summarize Long Email Threads","Extract decisions, open questions, owners and deadlines without inventing missing context.","Convert a sample thread into a four-part action summary."),
      lesson("Build Reusable Reply Patterns","Create adaptable structures for recurring communication while keeping each message specific.","Build one reusable reply template for a frequent request."),
      lesson("Review Tone, Accuracy and Confidentiality","Apply a human review that checks facts, recipients, tone, privacy and commitments before sending.","Use the five-point send check on an AI-assisted email."),
      lesson("Create Your Personal Email Workflow","Combine triage, drafting, review and follow-up into one repeatable process.","Document your email workflow as a checklist."),
    ],
  },
  {
    id:"meetings-into-action", title:"Meetings Into Action", status:"published", duration:"45 min", categories:["AI Workday","Meetings"],
    description:"Prepare better meetings, capture the important points and turn conversations into clear owners, actions and deadlines.",
    lessons:[
      lesson("Decide Whether a Meeting Is Needed","Choose between a meeting, written update or quick decision request based on the work required.","Replace one unnecessary meeting with a clearer asynchronous format."),
      lesson("Create a Focused Agenda","Define the decision, preparation and time boundary before people enter the room.","Write a decision-focused agenda for a recurring meeting."),
      lesson("Capture Decisions Without Writing Everything","Record outcomes, reasoning and unresolved questions instead of producing a transcript.","Take structured notes from a short meeting scenario."),
      lesson("Turn Notes Into Action Items","Convert discussion into specific actions with owners, deadlines and completion criteria.","Rewrite vague follow-ups as accountable action items."),
      lesson("Write a Useful Follow-Up","Create a short record that confirms decisions and exposes misunderstandings early.","Draft a meeting follow-up with decisions, actions and open questions."),
      lesson("Build a Repeatable Meeting Workflow","Connect preparation, capture, review and follow-up with clear human checks.","Save a reusable before-during-after meeting checklist."),
    ],
  },
  {
    id:"research-without-overwhelm", title:"Research Without the Overwhelm", status:"published", duration:"55 min", categories:["AI Workday","Research"],
    description:"Find, compare and summarize information with AI while checking evidence, uncertainty and unsupported claims.",
    lessons:[
      lesson("Start With the Decision, Not the Search","Define the decision and evidence threshold before gathering information.","Write a decision question and three criteria for useful evidence."),
      lesson("Ask Better Research Questions","Break a broad topic into answerable questions that reduce irrelevant searching.","Turn one vague topic into a focused research question tree."),
      lesson("Build a Source Plan","Choose primary, authoritative and independent sources appropriate to the claim.","Create a source plan that states what each source must prove."),
      lesson("Summarize Without Losing Context","Preserve conditions, limitations and disagreement when compressing source material.","Summarize a passage with its caveat and scope intact."),
      lesson("Compare Conflicting Information","Explain why sources disagree instead of forcing a false single answer.","Build a comparison table for two conflicting claims."),
      lesson("Check Claims and Uncertainty","Separate supported facts, inference and unknowns before using an AI-generated answer.","Label a sample brief’s statements as verified, inferred or unsupported."),
      lesson("Produce a Decision-Ready Brief","Present the decision, evidence, risks and next step in a format a busy reader can use.","Create a one-page decision brief from your research."),
    ],
  },
  {
    id:"documents-reports-faster", title:"Documents & Reports Faster", status:"published", duration:"55 min", categories:["AI Workday","Writing"],
    description:"Turn scattered notes into structured reports, proposals and updates through a reviewable human-and-AI workflow.",
    lessons:[
      lesson("Define the Reader and Outcome","Clarify who will read the document, what they need and what should happen next.","Write a one-sentence reader and outcome brief."),
      lesson("Build a Strong Document Outline","Organize evidence around the reader’s questions before generating prose.","Create a five-part outline for a real workplace document."),
      lesson("Convert Notes Into a First Draft","Use source notes and explicit constraints to create a draft without fabricating facts.","Generate a draft section that stays inside supplied evidence."),
      lesson("Improve Structure and Clarity","Edit for logic, headings, transitions and concise language instead of superficial polish.","Rewrite a dense section for scan-friendly clarity."),
      lesson("Add Evidence and Examples","Connect important claims to supporting data, sources or concrete examples.","Strengthen three unsupported claims with evidence placeholders."),
      lesson("Review for Errors and Generic Language","Find invented details, vague claims, repetition and language that does not sound like you.","Run an editorial and factual review on a sample draft."),
      lesson("Save a Reusable Document Workflow","Turn the successful sequence into a repeatable brief, draft and review template.","Save a document-production checklist for future work."),
    ],
  },
  {
    id:"automate-repetitive-work", title:"Automate Repetitive Work", status:"published", duration:"55 min", categories:["AI Workday","Automation"],
    description:"Find repeated tasks worth simplifying and design safe workflows using templates, AI and lightweight automation.",
    lessons:[
      lesson("Spot a Good Automation Opportunity","Prioritize frequent, predictable and reversible tasks while avoiding high-risk judgment.","Score one repeated task for frequency, predictability and risk."),
      lesson("Map the Current Process","Make inputs, steps, decisions and outputs visible before changing the workflow.","Draw the current process for a repeated administrative task."),
      lesson("Remove Unnecessary Steps","Eliminate duplication and unclear approvals before automating a bad process.","Remove or combine at least one unnecessary process step."),
      lesson("Choose Template, AI or Automation","Match the solution to variability: template for stable work, AI for interpretation, automation for fixed rules.","Select the simplest solution for three workflow scenarios."),
      lesson("Add Human Review Points","Place review where errors would be costly, irreversible or externally visible.","Mark the human approval points in your workflow."),
      lesson("Test Failure Cases","Test missing information, unusual inputs and service failure before relying on the workflow.","Write and run three failure-case tests."),
      lesson("Launch Your First Repeatable Workflow","Document ownership, monitoring and rollback so the workflow remains dependable.","Create a launch checklist and success measure for one workflow."),
    ],
  },
  {
    id:"spreadsheets-without-stress", title:"Spreadsheets Without the Stress", status:"draft", duration:"55 min", categories:["AI Workday","Data"],
    description:"Use AI to understand formulas, clean data and explain spreadsheet results while keeping sensitive information protected.",
    lessons:[
      lesson("Describe the Spreadsheet Problem Clearly","Explain the desired result, columns, examples and constraints before asking for a formula.","Write a precise spreadsheet problem statement."),
      lesson("Understand an Existing Formula","Translate a formula into plain language and identify its assumptions and edge cases.","Explain a sample formula step by step."),
      lesson("Create and Check a New Formula","Generate a formula from examples, then test normal, blank and unusual inputs.","Build a formula and a three-row test table."),
      lesson("Clean Inconsistent Data","Define consistent formats and transformations without silently changing meaning.","Create a safe cleaning plan for a messy column."),
      lesson("Summarize a Table","Choose calculations that answer a business question instead of summarizing everything.","Produce a short evidence-based table summary."),
      lesson("Find Errors Before They Spread","Use reconciliation, spot checks and boundary cases to catch spreadsheet errors.","Create an error-checking checklist for a recurring sheet."),
      lesson("Protect Sensitive Business Data","Remove or mask personal and confidential data before using external AI tools.","Prepare a privacy-safe version of a sample dataset."),
    ],
  },
  {
    id:"focus-ai-workday", title:"Focus in an AI Workday", status:"draft", duration:"45 min", categories:["AI Workday","Focus"],
    description:"Reduce distraction, start difficult work and use AI as a focused assistant instead of another source of interruption.",
    lessons:[
      lesson("Diagnose Your Distraction Pattern","Identify whether interruption, avoidance, ambiguity or low energy is breaking focus.","Complete a distraction trigger log."),
      lesson("Choose One Daily Outcome","Translate a broad priority into one visible result for the day.","Write tomorrow’s single daily outcome."),
      lesson("Build a Focus Sprint","Set a small scope, remove friction and define a stopping point before beginning.","Schedule and prepare one 25-minute focus sprint."),
      lesson("Use AI Without Losing Direction","Give AI a bounded role so exploration does not replace progress.","Write a focused AI brief with a clear endpoint."),
      lesson("Protect Communication Windows","Batch routine communication while preserving response expectations and urgent channels.","Design two communication windows and an escalation rule."),
      lesson("Review Focus and Energy","Use evidence from completed work and energy patterns to improve the next week.","Run a weekly focus review using three simple measures."),
    ],
  },
  {
    id:"ai-for-managers", title:"AI for Managers", status:"draft", duration:"55 min", categories:["AI Workday","Leadership"],
    description:"Use AI to prepare decisions, delegate clearly, coach team members and reduce administrative work without outsourcing leadership judgment.",
    lessons:[
      lesson("What Managers Should Never Delegate to AI","Keep accountability, sensitive judgment and people decisions with the manager.","Classify management tasks by assist, review carefully or human-only."),
      lesson("Prepare Better One-to-Ones","Turn context and observations into a useful agenda without creating a surveillance record.","Build a respectful one-to-one preparation template."),
      lesson("Turn Goals Into Clear Delegation","Define outcome, context, authority, constraints and check-in points.","Rewrite a vague request as a complete delegation brief."),
      lesson("Review Team Updates Efficiently","Extract blockers, decisions and risks while checking the original update.","Summarize sample updates into an action dashboard."),
      lesson("Compare Options Before a Decision","Use explicit criteria and uncertainty to challenge—not replace—manager judgment.","Create a decision matrix with risks and missing evidence."),
      lesson("Build Reusable Management Briefs","Standardize recurring preparation without making communication impersonal.","Create one reusable brief for hiring, planning or review."),
      lesson("Create a Safe Team AI Policy","Set practical rules for approved tools, confidential data, review and incident reporting.","Draft a one-page team AI working agreement."),
    ],
  },
  {
    id:"personal-ai-operating-system", title:"Build Your Personal AI Operating System", status:"draft", duration:"55 min", categories:["AI Workday","Advanced"],
    description:"Combine your most useful workflows into one trusted system for priorities, communication, knowledge and weekly improvement.",
    lessons:[
      lesson("Choose the Workflows Worth Keeping","Select workflows that are useful, repeatable and safe enough to maintain.","Review your workflows and keep only those with clear value."),
      lesson("Build a Trusted Capture System","Create one reliable place for commitments, ideas and incoming work.","Set up a capture inbox and processing rule."),
      lesson("Organize Active Projects","Keep project outcomes, next actions and supporting material connected.","Create a simple active-project dashboard."),
      lesson("Create Your Workflow Library","Store prompts, templates, examples and review rules together.","Document one workflow in a reusable library format."),
      lesson("Set Privacy and Review Rules","Apply consistent data handling and human approval standards across tools.","Write your personal AI safety checklist."),
      lesson("Run a Weekly System Review","Maintain trust by reviewing commitments, failures and changing priorities.","Complete a full system review using a saved checklist."),
      lesson("Build Your 90-Day Improvement Plan","Choose a small sequence of workflows and measures instead of attempting total transformation.","Create a 90-day roadmap with three workflow milestones."),
    ],
  },
];
